import { resolveFeatureFlags } from "@japangolearn/core";

export const featureFlags = resolveFeatureFlags({
  EXPO_PUBLIC_FEATURE_AI: process.env.EXPO_PUBLIC_FEATURE_AI,
  EXPO_PUBLIC_FEATURE_PREMIUM: process.env.EXPO_PUBLIC_FEATURE_PREMIUM,
  EXPO_PUBLIC_FEATURE_UNFINISHED_LEVELS: process.env.EXPO_PUBLIC_FEATURE_UNFINISHED_LEVELS,
  EXPO_PUBLIC_FEATURE_TEACHER_ONBOARDING: process.env.EXPO_PUBLIC_FEATURE_TEACHER_ONBOARDING,
  EXPO_PUBLIC_FEATURE_TEACHER_STUDIO: process.env.EXPO_PUBLIC_FEATURE_TEACHER_STUDIO,
  EXPO_PUBLIC_FEATURE_COURSE_CATALOG: process.env.EXPO_PUBLIC_FEATURE_COURSE_CATALOG,
  EXPO_PUBLIC_FEATURE_BUNNY_UPLOADS: process.env.EXPO_PUBLIC_FEATURE_BUNNY_UPLOADS,
  EXPO_PUBLIC_FEATURE_SECURE_PLAYBACK: process.env.EXPO_PUBLIC_FEATURE_SECURE_PLAYBACK,
  EXPO_PUBLIC_FEATURE_FREE_ENROLLMENT: process.env.EXPO_PUBLIC_FEATURE_FREE_ENROLLMENT,
  EXPO_PUBLIC_FEATURE_COMMERCE_WEB: process.env.EXPO_PUBLIC_FEATURE_COMMERCE_WEB,
  EXPO_PUBLIC_FEATURE_TEACHER_EARNINGS: process.env.EXPO_PUBLIC_FEATURE_TEACHER_EARNINGS,
  EXPO_PUBLIC_FEATURE_TEACHER_PAYOUTS: process.env.EXPO_PUBLIC_FEATURE_TEACHER_PAYOUTS,
  EXPO_PUBLIC_FEATURE_MOBILE_PURCHASES: process.env.EXPO_PUBLIC_FEATURE_MOBILE_PURCHASES,
  EXPO_PUBLIC_FEATURE_TEACHER_MOBILE_MODE: process.env.EXPO_PUBLIC_FEATURE_TEACHER_MOBILE_MODE,
});
