import { resolveFeatureFlags } from "@japangolearn/core";

export const featureFlags = resolveFeatureFlags({
  NEXT_PUBLIC_FEATURE_AI: process.env.NEXT_PUBLIC_FEATURE_AI,
  NEXT_PUBLIC_FEATURE_PREMIUM: process.env.NEXT_PUBLIC_FEATURE_PREMIUM,
  NEXT_PUBLIC_FEATURE_UNFINISHED_LEVELS: process.env.NEXT_PUBLIC_FEATURE_UNFINISHED_LEVELS,
  NEXT_PUBLIC_FEATURE_TEACHER_ONBOARDING: process.env.NEXT_PUBLIC_FEATURE_TEACHER_ONBOARDING,
  NEXT_PUBLIC_FEATURE_TEACHER_STUDIO: process.env.NEXT_PUBLIC_FEATURE_TEACHER_STUDIO,
  NEXT_PUBLIC_FEATURE_COURSE_CATALOG: process.env.NEXT_PUBLIC_FEATURE_COURSE_CATALOG,
  NEXT_PUBLIC_FEATURE_BUNNY_UPLOADS: process.env.NEXT_PUBLIC_FEATURE_BUNNY_UPLOADS,
  NEXT_PUBLIC_FEATURE_SECURE_PLAYBACK: process.env.NEXT_PUBLIC_FEATURE_SECURE_PLAYBACK,
  NEXT_PUBLIC_FEATURE_FREE_ENROLLMENT: process.env.NEXT_PUBLIC_FEATURE_FREE_ENROLLMENT,
  NEXT_PUBLIC_FEATURE_COMMERCE_WEB: process.env.NEXT_PUBLIC_FEATURE_COMMERCE_WEB,
  NEXT_PUBLIC_FEATURE_TEACHER_EARNINGS: process.env.NEXT_PUBLIC_FEATURE_TEACHER_EARNINGS,
  NEXT_PUBLIC_FEATURE_TEACHER_PAYOUTS: process.env.NEXT_PUBLIC_FEATURE_TEACHER_PAYOUTS,
  NEXT_PUBLIC_FEATURE_MOBILE_PURCHASES: process.env.NEXT_PUBLIC_FEATURE_MOBILE_PURCHASES,
  NEXT_PUBLIC_FEATURE_TEACHER_MOBILE_MODE: process.env.NEXT_PUBLIC_FEATURE_TEACHER_MOBILE_MODE,
});
