/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false cloudflare-env.d.ts` (hash: 2658ddeb4301f62abc357bcb1ee7bcd0)
interface __BaseEnv_Env {
	APP_ENV: "staging" | "production";
	ALLOWED_ORIGINS: "http://localhost:3000" | "https://japangolearn.com,https://www.japangolearn.com,http://localhost:3000,http://127.0.0.1:3000";
	SUPABASE_URL: string;
	SUPABASE_PUBLISHABLE_KEY: string;
	BUNNY_STREAM_LIBRARY_ID: string;
	BUNNY_STREAM_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		APP_ENV: "staging";
		ALLOWED_ORIGINS: "http://localhost:3000";
		SUPABASE_URL: string;
		SUPABASE_PUBLISHABLE_KEY: string;
		BUNNY_STREAM_LIBRARY_ID: string;
		BUNNY_STREAM_API_KEY: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "ALLOWED_ORIGINS" | "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY" | "BUNNY_STREAM_LIBRARY_ID" | "BUNNY_STREAM_API_KEY">> {}
}
